import re,sys,io
sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding="utf-8",errors="replace")
h=open("admin_dashboard.html",encoding="utf-8",errors="replace").read()
print("=== ALL ADMIN API CALLS (ADMIN + ...) ===")
calls=set(re.findall(r"ADMIN\s*\+\s*[\"`]([^\"`]+)[\"`]",h))
for c in sorted(calls): print("  /mgr-admin-8bcde2021d98"+c)
print()
print("=== ALL fetch() targets ===")
for m in sorted(set(re.findall(r"fetch\(\s*[`\"]([^`\"]+)[`\"]",h))): print("  ",m)
print()
print("=== methods ===")
for m in sorted(set(re.findall(r"method:\s*[\"']([A-Z]+)[\"']",h))): print("  ",m)
print()
print("=== mode names / telegram ===")
for m in re.findall(r"modeNames\s*=\s*\{[^}]+\}",h): print("  ",m)
print()
print("=== telegram / bot refs ===")
for m in sorted(set(re.findall(r"(?:telegram|bot|t\.me|api\.telegram)[A-Za-z0-9_./:\-]*",h,re.I))): print("  ",m)
