package initialize

import (
	"os"

	"github.com/flipped-aurora/gin-vue-admin/server/global"
	app "github.com/flipped-aurora/gin-vue-admin/server/model/app"
	"github.com/flipped-aurora/gin-vue-admin/server/model/system"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Gorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func Gorm() *gorm.DB {
	switch global.GVA_CONFIG.System.DbType {
	case "mysql":
		return GormMysql()
	case "pgsql":
		return GormPgSql()
	default:
		return GormMysql()
	}
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表
		system.SysApi{},
		system.SysUser{},
		system.SysBaseMenu{},
		system.JwtBlacklist{},
		system.SysAuthority{},
		system.SysDictionary{},
		system.SysOperationRecord{},
		system.SysAutoCodeHistory{},
		system.SysDictionaryDetail{},
		system.SysBaseMenuParameter{},
		system.SysBaseMenuBtn{},
		system.SysAuthorityBtn{},
		system.SysAutoCode{},

		// ★★ T26（R2-1 实测补充）：业务表也必须建，否则空库启动时
		//   `core/server.go` 的 `blockchain.LoadRpcList()` 会因
		//   `Table 'xxx.token' doesn't exist` 而 panic，
		//   且 `/app/*` 等业务端点全部 500。
		//   ⇒ 把业务 model 一并纳入 AutoMigrate（幂等）。
		//
		//   ★ 类型名取自 `model/app/*.go` 的【实读】结果（10 个 struct，
		//     均实现了 TableName()）。AutoMigrate 只新增缺失的表/列，
		//     不改动已有数据。
		app.Agent{},
		app.BatchBill{},
		app.Bill{},
		app.Custom{},
		app.Machine{},
		app.Packet{},
		app.Settlement{},
		app.Token{},
		app.Wallet{},
		app.WalletBalance{},

		// 自动化模块表
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

		// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	)
	if err != nil {
		global.GVA_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.GVA_LOG.Info("register table success")
}
