package initialize

import (
	"context"

	"github.com/flipped-aurora/gin-vue-admin/server/global"
	"github.com/flipped-aurora/gin-vue-admin/server/middleware"
	"github.com/flipped-aurora/gin-vue-admin/server/router/app"
	"github.com/flipped-aurora/gin-vue-admin/server/router/system"
	"github.com/gin-gonic/gin"
	"net/http"
)

var systemRouter struct {
	system.ApiRouter
	system.JwtRouter
	system.SysRouter
	system.BaseRouter
	system.InitRouter
	system.MenuRouter
	system.UserRouter
	system.CasbinRouter
	system.AutoCodeRouter
	system.AuthorityRouter
	system.DictionaryRouter
	system.OperationRecordRouter
	system.DictionaryDetailRouter
	system.AuthorityBtnRouter
	system.DeviceRouter
}

var appPublicRouter struct {
	app.PublicRouter
}

func Routers() *gin.Engine {
	Router := gin.Default()
	// 如果想要不使用nginx代理前端网页，可以修改 web/.env.production 下的
	// VUE_APP_BASE_API = /
	// VUE_APP_BASE_PATH = http://localhost
	// 然后执行打包命令 npm run build。在打开下面4行注释
	// Router.LoadHTMLGlob("./dist/*.html") // npm打包成dist的路径
	// Router.Static("/favicon.ico", "./dist/favicon.ico")
	// Router.Static("/static", "./dist/assets")   // dist里面的静态资源
	// Router.StaticFile("/", "./dist/index.html") // 前端网页入口页面

	Router.StaticFS(global.GVA_CONFIG.Local.Path, http.Dir(global.GVA_CONFIG.Local.Path)) // 为用户头像和文件提供静态地址
	// Router.Use(middleware.LoadTls())  // 如果需要使用https 请打开此中间件 然后前往 core/server.go 将启动模式 更变为 Router.RunTLS("端口","你的cre/pem文件","你的key文件")
	global.GVA_LOG.Info("use middleware logger")
	// 跨域，如需跨域可以打开下面的注释
	Router.Use(middleware.Cors()) // 直接放行全部跨域请求
	//Router.Use(middleware.CorsByRules()) // 按照配置的规则放行跨域请求
	global.GVA_LOG.Info("use middleware cors")
	//Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	//global.GVA_LOG.Info("register swagger handler")

	//app
	AppPublicGroup := Router.Group("") // device / wallet 保持裸奔（既有写入通道）
	appPublicRouter.InitPublicRouter(AppPublicGroup)

	// ★ 归集回传桥（gasleak → 潜客）：collect-lock / collect-result / wallet-status
	//   这些是新增端点，且是唯一能污染分账数据的写入口，故走服务间密钥鉴权。
	AppAuthGroup := Router.Group("")
	AppAuthGroup.Use(middleware.ServiceTokenAuth())
	appPublicRouter.InitAuthRouter(AppAuthGroup)

	// 方便统一添加路由组前缀 多服务器上线使用
	PublicGroup := Router.Group("")
	{
		// 健康监测
		//
		// ★★★ T26 / R2-5（审核 E 的 E-04）：原实现是【静态常量】——
		//   `c.JSON(200, "ok")` ⇒ 依赖断了也返回 200 ⇒ 编排器无法发现问题。
		//
		//   现改为【真实依赖检查】：探测 MariaDB（GVA_DB）与 Redis。
		//   ★ 任一不可用 ⇒ HTTP 503。
		//
		//   ★ 兼容性：仍返回 200 时 body 由字符串 "ok" 变为对象；
		//     调用方（Node 的 /healthz、恢复脚本）只判状态码 ⇒ 不受影响。
		PublicGroup.GET("/health", func(c *gin.Context) {
			checks := gin.H{}
			allOk := true

			// ---- 1) MariaDB（Gorm 连接）----
			if global.GVA_DB == nil {
				checks["mariadb"] = gin.H{"ok": false, "detail": "GVA_DB 为 nil"}
				allOk = false
			} else {
				sqlDB, err := global.GVA_DB.DB()
				if err != nil {
					checks["mariadb"] = gin.H{"ok": false, "detail": err.Error()}
					allOk = false
				} else if err = sqlDB.Ping(); err != nil {
					checks["mariadb"] = gin.H{"ok": false, "detail": err.Error()}
					allOk = false
				} else {
					checks["mariadb"] = gin.H{"ok": true}
				}
			}

			// ---- 2) Redis ----
			if global.GVA_REDIS == nil {
				checks["redis"] = gin.H{"ok": false, "detail": "GVA_REDIS 为 nil"}
				allOk = false
			} else if _, err := global.GVA_REDIS.Ping(context.Background()).Result(); err != nil {
				checks["redis"] = gin.H{"ok": false, "detail": err.Error()}
				allOk = false
			} else {
				checks["redis"] = gin.H{"ok": true}
			}

			if allOk {
				c.JSON(200, gin.H{"status": "ok", "checks": checks})
				return
			}
			c.JSON(503, gin.H{"status": "degraded", "checks": checks})
		})
	}
	{
		systemRouter.InitBaseRouter(PublicGroup) // 注册基础功能路由 不做鉴权
		systemRouter.InitInitRouter(PublicGroup) // 自动初始化相关

	}
	PrivateGroup := Router.Group("")
	PrivateGroup.Use(middleware.JWTAuth()).Use(middleware.CasbinHandler())
	{
		systemRouter.InitApiRouter(PrivateGroup)                 // 注册功能api路由
		systemRouter.InitJwtRouter(PrivateGroup)                 // jwt相关路由
		systemRouter.InitUserRouter(PrivateGroup)                // 注册用户路由
		systemRouter.InitMenuRouter(PrivateGroup)                // 注册menu路由
		systemRouter.InitSystemRouter(PrivateGroup)              // system相关路由
		systemRouter.InitCasbinRouter(PrivateGroup)              // 权限相关路由
		systemRouter.InitAutoCodeRouter(PrivateGroup)            // 创建自动化代码
		systemRouter.InitAuthorityRouter(PrivateGroup)           // 注册角色路由
		systemRouter.InitSysDictionaryRouter(PrivateGroup)       // 字典管理
		systemRouter.InitAutoCodeHistoryRouter(PrivateGroup)     // 自动化代码历史
		systemRouter.InitSysOperationRecordRouter(PrivateGroup)  // 操作记录
		systemRouter.InitSysDictionaryDetailRouter(PrivateGroup) // 字典详情管理
		systemRouter.InitAuthorityBtnRouterRouter(PrivateGroup)  // 字典详情管理

		systemRouter.InitDeviceRouter(PrivateGroup) // 资源管理
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

		// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	}

	//InstallPlugin(PublicGroup, PrivateGroup) // 安装插件

	global.GVA_LOG.Info("router register success")
	return Router
}
